package net.pvytykac.jpaspec;

import net.pvytykac.jpaspec.api.ItemsFilter;
import net.pvytykac.jpaspec.db.ItemDbo;
import net.pvytykac.jpaspec.db.ItemRepository;
import net.pvytykac.jpaspec.queryfilter.StringFilter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Pageable;
import org.springframework.test.context.ContextConfiguration;

import java.math.BigDecimal;
import java.util.Set;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

// copy to make sure there's no db level cross fire when multiple instances of repository tests are running
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = PostgresContainerInitializer.class)
class AnotherItemRepositoryTest {

    @Autowired
    private ItemRepository repository;

    @Test
    void save_idAutoGenerated() {
        var dbo = givenDbo();

        var saved = repository.save(dbo);

        assertThat(saved)
                .returns(dbo.getName(), ItemDbo::getName)
                .returns(dbo.getPrice(), ItemDbo::getPrice)
                .returns(dbo.getStatus(), ItemDbo::getStatus)
                .extracting(ItemDbo::getId)
                .isNotNull();

        assertThat(repository.count())
                .isEqualTo(1L);
    }

    @ParameterizedTest
    @MethodSource("matchingItemsFilters")
    void findAll_ItemsFilter_DoesMatch(ItemsFilter filter) {
        repository.save(givenDbo());

        assertThat(repository.findAll(filter, Pageable.unpaged()))
                .hasSize(1);
    }

    @ParameterizedTest
    @MethodSource("nonMatchingItemsFilters")
    void findAll_ItemsFilter_DoesNotMatch(ItemsFilter filter) {
        repository.save(givenDbo());

        assertThat(repository.findAll(filter, Pageable.unpaged()))
                .isEmpty();
    }

    @Test
    void findAll_IdFilter_DoesMatch() {
        var saved = repository.save(givenDbo());

        assertThat(repository.findAll(new ItemsFilter().setId(saved.getId().toString()), Pageable.unpaged()))
                .hasSize(1);
    }

    @Test
    void findAll_IdFilter_DoesNotMatch() {
        repository.save(givenDbo());

        assertThat(repository.findAll(new ItemsFilter().setId(UUID.randomUUID().toString()), Pageable.unpaged()))
                .isEmpty();
    }

    static ItemsFilter[] matchingItemsFilters() {
        return new ItemsFilter[]{
                new ItemsFilter().setName("Juic").setNameOperator(StringFilter.Operator.STARTS_WITH),
                new ItemsFilter().setName("uice").setNameOperator(StringFilter.Operator.ENDS_WITH),
                new ItemsFilter().setName("uic").setNameOperator(StringFilter.Operator.CONTAINS),
                new ItemsFilter().setName("Juice").setNameOperator(StringFilter.Operator.EXACT_MATCH),
                new ItemsFilter().setStatus(Set.of("PENDING")),
                new ItemsFilter().setStatus(Set.of("PENDING", "ACTIVE", "DISABLED")),
        };
    }

    static ItemsFilter[] nonMatchingItemsFilters() {
        return new ItemsFilter[]{
                new ItemsFilter().setName("uice").setNameOperator(StringFilter.Operator.STARTS_WITH),
                new ItemsFilter().setName("Juic").setNameOperator(StringFilter.Operator.ENDS_WITH),
                new ItemsFilter().setName("Juices").setNameOperator(StringFilter.Operator.CONTAINS),
                new ItemsFilter().setName("uic").setNameOperator(StringFilter.Operator.EXACT_MATCH),
                new ItemsFilter().setStatus(Set.of("ACTIVE", "DISABLED")),
        };
    }

    private ItemDbo givenDbo() {
        return ItemDbo.builder()
                .name("Juice")
                .price(BigDecimal.valueOf(24.99D))
                .status(ItemDbo.Status.PENDING)
                .build();
    }
}
