package net.pvytykac.jpaspec;

import net.pvytykac.jpaspec.db.ItemDbo;
import net.pvytykac.jpaspec.db.ItemDbo.Status;
import net.pvytykac.jpaspec.db.ItemRepository;
import net.pvytykac.jpaspec.db.ItemsFilter;
import net.pvytykac.jpaspec.queryfilter.EnumFilter;
import net.pvytykac.jpaspec.queryfilter.StringFilter;
import net.pvytykac.jpaspec.queryfilter.UuidFilter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.data.domain.Pageable;
import org.springframework.test.context.ContextConfiguration;

import java.math.BigDecimal;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = PostgresContainerInitializer.class)
class ItemRepositoryTest {

    @Autowired
    private ItemRepository repository;

    @Test
    void save_idAutoGenerated() {
        var dbo = givenDbo();

        var saved = repository.save(dbo);

        assertThat(saved)
                .returns(dbo.getName(), ItemDbo::getName)
                .returns(dbo.getPrice(), ItemDbo::getPrice)
                .returns(dbo.getStatus(), ItemDbo::getStatus)
                .extracting(ItemDbo::getId)
                .isNotNull();

        assertThat(repository.count())
                .isEqualTo(1L);
    }

    @ParameterizedTest
    @MethodSource("matchingItemsFilters")
    void findAll_ItemsFilter_DoesMatch(ItemsFilter filter) {
        repository.save(givenDbo());

        assertThat(repository.findAll(filter, Pageable.unpaged()))
                .hasSize(1);
    }

    @ParameterizedTest
    @MethodSource("nonMatchingItemsFilters")
    void findAll_ItemsFilter_DoesNotMatch(ItemsFilter filter) {
        repository.save(givenDbo());

        assertThat(repository.findAll(filter, Pageable.unpaged()))
                .isEmpty();
    }

    @Test
    void findAll_IdFilter_DoesMatch() {
        var saved = repository.save(givenDbo());
        var filter = ItemsFilter.builder().uuidFilter(UuidFilter.equalTo(saved.getId())).build();

        assertThat(repository.findAll(filter, Pageable.unpaged()))
                .hasSize(1);
    }

    @Test
    void findAll_IdFilter_DoesNotMatch() {
        repository.save(givenDbo());
        var filter = ItemsFilter.builder().uuidFilter(UuidFilter.equalTo(UUID.randomUUID())).build();

        assertThat(repository.findAll(filter, Pageable.unpaged()))
                .isEmpty();
    }

    static ItemsFilter[] matchingItemsFilters() {
        return new ItemsFilter[]{
                ItemsFilter.builder().nameFilter(StringFilter.startsWith("Juic")).build(),
                ItemsFilter.builder().nameFilter(StringFilter.endsWith("uice")).build(),
                ItemsFilter.builder().nameFilter(StringFilter.contains("uic")).build(),
                ItemsFilter.builder().nameFilter(StringFilter.equalTo("Juice")).build(),
                ItemsFilter.builder().statusFilter(EnumFilter.of(Status.PENDING)).build(),
                ItemsFilter.builder().statusFilter(EnumFilter.of(Status.PENDING, Status.ACTIVE, Status.DISABLED)).build(),
        };
    }

    static ItemsFilter[] nonMatchingItemsFilters() {
        return new ItemsFilter[]{
                ItemsFilter.builder().nameFilter(StringFilter.startsWith("uice")).build(),
                ItemsFilter.builder().nameFilter(StringFilter.endsWith("Juic")).build(),
                ItemsFilter.builder().nameFilter(StringFilter.contains("Juices")).build(),
                ItemsFilter.builder().nameFilter(StringFilter.equalTo("uic")).build(),
                ItemsFilter.builder().statusFilter(EnumFilter.of(Status.ACTIVE, Status.DISABLED)).build(),
        };
    }

    private ItemDbo givenDbo() {
        return ItemDbo.builder()
                .name("Juice")
                .price(BigDecimal.valueOf(24.99D))
                .status(Status.PENDING)
                .build();
    }
}
